name: fuodz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.72+84

environment:
  sdk: ^3.7.2

# Essential dependencies only - cleaned up for simplicity
dependencies:
  # Flutter Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # International phone number input
  intl_phone_field: ^3.2.0
  
  # Firebase - Core Backend
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.1.2
  firebase_crashlytics: ^4.1.2
  
  # State Management
  stacked: ^3.4.0
  provider: ^6.1.1
  
  # UI & Design
  velocity_x: ^4.3.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Navigation & Routing
  google_nav_bar: ^5.0.3
  
  # Location & Maps (Critical for drivers)
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.1
  flutter_polyline_points: ^1.0.0
  permission_handler: ^12.0.0+1
  map_launcher: ^3.5.0
  
  # HTTP & Networking
  dio: ^5.8.0+1
  
  # Utilities
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  jiffy: ^6.4.3
  intl: ^0.18.1
  
  # Notifications (Critical for order alerts)
  awesome_notifications: ^0.10.1
  
  # Forms & Input
  flutter_form_builder: ^10.0.1
  
  # Rating (for driver ratings)
  flutter_rating_bar: ^4.0.1
  
  # Background services (for location tracking)
  flutter_background: ^1.1.0

dependency_overrides:
  archive: ^3.6.1
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  http: ^0.13.0
  intl: ^0.18.1
  just_audio: ^0.10.3
  url_launcher_ios: ^6.3.1
  webview_flutter_android: ^4.4.2
  flutter_widget_from_html: null
  flutter_widget_from_html_core: null
  fwfh_webview: null
  fwfh_cached_network_image: null
  fwfh_chewie: null
  fwfh_just_audio: null
  fwfh_svg: null
  fwfh_url_launcher: null

dev_dependencies:
  flutter_application_id: ^2.0.0-dev
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  translator: ^0.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#5e17eb"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
    - assets/json/
    - assets/lang/
