// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmUafz431YLkL6d1tNL9qv5cuHC1TkDw',
    appId: '1:156854442550:web:f96d46d9f1c961983b9697',
    messagingSenderId: '156854442550',
    projectId: 'classyapp-unified-backend',
    authDomain: 'classyapp-unified-backend.firebaseapp.com',
    databaseURL: 'https://classyapp-unified-backend.firebaseio.com',
    storageBucket: 'classyapp-unified-backend.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugyfh2vjI7gHqGb6uRCmAKNV0xWG_Xrs',
    appId: '1:156854442550:android:f96d46d9f1c961983b9697',
    messagingSenderId: '156854442550',
    projectId: 'classyapp-unified-backend',
    storageBucket: 'classyapp-unified-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmUafz431YLkL6d1tNL9qv5cuHC1TkDw',
    appId: '1:156854442550:ios:324810390e6ce95e3b9697',
    messagingSenderId: '156854442550',
    projectId: 'classyapp-unified-backend',
    storageBucket: 'classyapp-unified-backend.firebasestorage.app',
    iosBundleId: 'com.classy.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASmUafz431YLkL6d1tNL9qv5cuHC1TkDw',
    appId: '1:156854442550:ios:324810390e6ce95e3b9697',
    messagingSenderId: '156854442550',
    projectId: 'classyapp-unified-backend',
    storageBucket: 'classyapp-unified-backend.firebasestorage.app',
    iosBundleId: 'com.classy.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASmUafz431YLkL6d1tNL9qv5cuHC1TkDw',
    appId: '1:156854442550:web:f96d46d9f1c961983b9697',
    messagingSenderId: '156854442550',
    projectId: 'classyapp-unified-backend',
    authDomain: 'classyapp-unified-backend.firebaseapp.com',
    storageBucket: 'classyapp-unified-backend.firebasestorage.app',
  );
}
